name: Wait for Comment and Send to URL

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  repository-projects: read
  pull-requests: read

jobs:
  process_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null && startsWith(github.event.comment.body, '/associate')
    steps:
      - name: Check for "/associate" comment and extract XY
        run: |
          # Extract the part after "/associate "
          BRANCH=$(echo "${{ github.event.comment.body }}" | sed 's/^\/associate //')
          
          # Check if the value is not empty
          if [[ -n "$BRANCH" ]]; then
            echo "Sending association: $BRANCH"
            
            curl 'https://github.com/_graphql' \
              -H 'accept: application/json' \
              --data-raw '{"query":"1ed695200ca0b6cac0e012fd4926b664","variables":{"baseIssueId":"I_kwDONyyOks6wU-tS","linkingIds":["MDM6UmVmMzg1MzcxNzkzOnJlZnMvaGVhZHMvcGxheWVyLWp1ZGdlLXN0YXJ0LXJpc2U="]}}'
          else
            echo "No valid association value found."
          fi
