name: Assign Issue on Claim

on:
  issue_comment:
    types: [created]
concurrency: issues

permissions:
  issues: write
  repository-projects: read
  pull-requests: read

jobs:
  claim-issue:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null && startsWith(github.event.comment.body, '/claim')
    steps:
      - name: Assign issue to commenter
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: ${{ github.event.comment.user.login }}

      - name: Delete comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'delete-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
